### ISSUE TITLE
https://api.mixpanel.com api rejected some items

### ISSUE THREAD

**Issue by nikunjazilen** [mixpanel/mixpanel-swift#326] opened 2019-09-04 06:25 UTC
Hi,

Yesterday it was working fine but today any event tracking is not log in MixPanel console.

> Pod Version: 2.6.5

Error as below:

> [Mixpanel - FlushRequest.swift - func flushRequestHandler(_:resource:completion:)] (info) - https://api.mixpanel.com api rejected some items

        

Code:
> Mixpanel.initialize(token: RDSettings.MIXPANEL_TOKEN_KEY)
>         Mixpanel.mainInstance().loggingEnabled = true
>         Mixpanel.mainInstance().flushInterval = 5

Please let me know the issue. Is it from MixPanel server side issue?

Thanks in advance.

**Comment by zihejia** [comment] 2019-09-05 06:47
hi @nikunjazilen , do you still have the issue? It the problem exists, you may contact Mixpanel support, I don't think it's a sdk related issue.

**Comment by nikunjazilen** [comment] 2019-09-05 07:16
Sometimes its not working and now its working fine. So there is sdk issue or Mixpanel server issue will does not show the log in console?

**Comment by cmcaboy** [comment] 2020-02-22 16:00
@nikunjazilen Did you ever find a root cause or solution?

**Comment by cmcaboy** [comment] 2020-02-25 03:10
After further investigation, it appears the local queue is capped at 50 events. Any subsequent event is not captured until the queue is flushed to the server. We were able to work around this issue by lowering the flush interval to 10 seconds.

**Comment by ybrikeeg** [comment] 2020-04-09 13:03
I am seeing this issue too. I have tried creating a new Mixpanel project, a new Xcode project, setting App Transport Security Settings to load arbitrary loads, but nothing works. It was working fine for me a few days ago.

**Comment by ybrikeeg** [comment] 2020-04-09 13:37
The issue is fixed when switching to VPN. Not sure why this happened, but at least it works for now.

**Comment by zihejia** [comment] 2020-04-21 00:00
I'm going to close this one now since it seems not a sdk related issue. No worries @cmcaboy , let's keep https://github.com/mixpanel/mixpanel-swift/issues/350 open to track the issue you mentioned.

**Closed by zihejia** 2020-04-21 00:00 UTC
