### ISSUE TITLE
Crash when using with Khan/SwiftTweaks

### ISSUE THREAD

**Issue by tomekh7** [mixpanel/mixpanel-swift#111] opened 2017-07-24 11:51 UTC
There is a conflict in naming while unarchiving in `loadFromDisk` function which causes a crash. It looks like you copied Khan/SwiftTweaks and modified it without changing location of the file where tweaks data is stored. So when we use Khan/SwiftTweaks as well, we have crash even if we don't enable Khan's tweaks for production build, but we use Mixpanel experiments for A/B testing.

> The application crash with the message: `Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: '*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (Data) for key (root); the class may be defined in source code or a library that is not linked'

**Comment by yarneo** [comment] 2017-07-24 16:16
Thanks for reporting this @tomekh7 and especially for finding out the root cause! I will be working on this and sending out a new release by tomorrow. 

Thanks again and sorry for the inconvenience. Will update this thread accordingly on progress.

**Comment by yarneo** [comment] 2017-07-27 00:28
fixed in v2.2.0!

**Closed** 2017-07-27 00:29 UTC
