### ISSUE TITLE
Unable to use Mixpanel-swift for swift4 in my framework

### ISSUE THREAD

**Issue by sagardesai16** [mixpanel/mixpanel-swift#171] opened 2018-01-05 09:46 UTC
Hi There,

I'm unable to use Mixpanel-swift in my framework via cocoa pod spec(dependency). As i get numerous errors(Screenshot attached). 

![screen shot 2018-01-05 at 2 14 08 pm](https://user-images.githubusercontent.com/11264990/34603805-6612701a-f22b-11e7-9962-9389a941349b.png)
.

**Comment by pchien** [comment] 2018-01-08 19:42
@sagardesai16 I just checked this with a test project. The test project is quite basic, but I didn't have any errors with the SDK. Is your project set up for Swift 4? The master branch is now on Swift 4. If you want to use Swift 3, please point to the v2.2.3 release

**Comment by MatheusCavalca** [comment] 2018-01-14 19:01
I am facing a similar issue, I'm trying to update my repo with the last version of my pod that uses Mixpanel-swift and Swift 4. I am using `pod repo push ...` command and it has several compilation errors:

<img width="485" alt="screen shot 2018-01-14 at 16 59 19" src="https://user-images.githubusercontent.com/6074082/34919512-82144496-f94c-11e7-8d33-cb9140e049da.png">

**Comment by piccoloaiutante** [comment] 2018-01-15 09:38
I just tried to add mixpanle pod on a swift 4 project and got few errors:

<img width="270" alt="screen shot 2018-01-15 at 10 38 03" src="https://user-images.githubusercontent.com/867842/34936043-3914652a-f9e0-11e7-8bbd-619dab2ab180.png">

**Comment by pchien** [comment] 2018-01-16 18:46
@MatheusCavalca @piccoloaiutante are you sure you're using Swift 4? The attributed string errors are the exact errors I got when my project was on Swift 3 but I was trying to integrate the latest version of the library, which is on Swift 4.

**Comment by ngaddamLogitech** [comment] 2018-02-08 22:49
@piccoloaiutante @pchien i got the same error.. does anyone know how to fix it?

**Comment by zyxsimonxyz** [comment] 2018-03-07 10:26
i am using swift 4 and facing the similar issue, can anyone help?

**Comment by zyxsimonxyz** [comment] 2018-03-07 10:43
try edit your podfile like this:
<img width="949" alt="2018-03-07 18 41 00" src="https://user-images.githubusercontent.com/6747811/37088066-1c5520f8-2237-11e8-8657-1cb54d85ffc2.png">

i think this issue is caused by we are not using the branch master.
so try using this call:
pod 'Mixpanel-swift', :git => 'https://github.com/mixpanel/mixpanel-swift.git'

**Comment by Parameshvadivel** [comment] 2018-05-03 10:08
is this cleared

**Comment by zihejia** [comment] 2018-05-03 17:03
Hi @Parameshvadivel, did you try the latest version? We just fixed some compile issues for swift4.

**Comment by zihejia** [comment] 2018-05-14 23:49
In swift version v2.4.1, we fixed the swift compile issue, so close this one for now, happy for anyone to reopen it if the problem still exists.

**Closed by zihejia** 2018-05-14 23:49 UTC
