### ISSUE TITLE
Mixpanel swift is failing to build with error `frame is only available on iOS 12.0 or newer`

### ISSUE THREAD

**Issue by YaliWang0523** [mixpanel/mixpanel-swift#255] opened 2018-10-08 03:27 UTC
using Swift 3 Xcode 10
pod 'Mixpanel-swift', '~>2.2.3'

**Comment by zihejia** [comment] 2018-10-08 03:41
Hi @YaliWang0523 , if you use Xcode 10, please upgrade to our latest version 2.5.1. If you need to stick to 2.2.3, here is the workaround:
Search '$0.frame.origin.y < $1.frame.origin.y' in ObjectFilter.swift, replace it with `($0 as! UITableViewCell).frame.origin.y < ($1 as! UITableViewCell).frame.origin.y`

I'm closing this one now, this is duplicated with issue https://github.com/mixpanel/mixpanel-swift/issues/240.

Please feel free to reopen it if the problem is still there.

**Closed by zihejia** 2018-10-08 03:41 UTC
