### ISSUE TITLE
[2.7.0] Events beyond batch limit being dropped

### ISSUE THREAD

**Issue by akhilpothana** [mixpanel/mixpanel-swift#350] opened 2020-02-25 23:10 UTC
We're having an issue with events past the batch limit of 50 being dropped and not showing up on the web console despite being tracked to the Mixpanel SDK. We're using the default `flushInterval` of 60 seconds.

**Steps to reproduce**:

1. Open the app for the first time, and start navigating to trigger events
2. Trigger over 50 events in less than 60 seconds
3. When 50 events have been queued, they are flushed to server (And the flush timer restarts)
4. Continue to use app and trigger more events

**Expected:** On the next flush, the second set of events appear
**Actual:** Any events triggered between the time the first flush occurred and 60 seconds later are dropped. After 60 seconds have passed from the time of the first flush, any newly triggered events appear.

Starting from the bottom, the red line denotes 50 events tracked. This is where the first flush occurs. The red line itself represents 60 seconds. There are events that are supposed to appear where the line is drawn. All events after the line are events that were triggered after 60 seconds had passed from the time of first flush.
<img width="777" alt="Screen Shot 2020-02-26 at 12 38 09 AM" src="https://user-images.githubusercontent.com/16505155/75315571-10fed780-5831-11ea-9dda-0e2fd2afedc7.png">

Our current solution is to manually set `flushInterval = 10`. This works because it's impossible to trigger more than 50 events within 10 seconds, and as a result, the flush is triggered by hitting the `flushInterval` and not the batch size limit. So every 10 seconds, we see all our expected events. We tested with a higher value like `300` and the behavior was the same as described earlier, except now we had to wait 5 minutes before any new events were tracked again. 

We're still interested in understanding what's going on, so we'd appreciate any help! Happy to provide any other details you may need.

**Comment by cmcaboy** [comment] 2020-02-26 15:00
I am running into this issue as well. It seems that once the batch queue is full, it cannot add anymore events until the flush interval is hit.

I can think of 2 possible solutions:
1) Flush the queue when the batch size limit is hit.
2) An an option to change the batch size.

**Comment by zihejia** [comment] 2020-04-24 00:18
Hi @akhilpothana @cmcaboy The issue has been fixed in v2.7.1. https://github.com/mixpanel/mixpanel-swift/releases/tag/v2.7.1.  Now events won't be dropped if over the batch limit. It was caused by a typo in code since v2.6.4 due to a change in the flush logic.  
Again, thanks for bringing this up and sorry for the late response. 

I'm closing this one now, please feel free to reopen it if the problem still exists.

**Closed by zihejia** 2020-04-24 00:18 UTC
