### ISSUE TITLE
Could not find module 'Mixpanel' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator

### ISSUE THREAD

**Issue by JZ-at-TP** [mixpanel/mixpanel-swift#571] opened 2022-12-07 19:50 UTC
We've got x86 and M1 apple macs  and we are trying to get our build to work on both. I'm on a M1 and I keep getting the following error:

Could not find module 'Mixpanel' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: /Users/USER/Library/Developer/Xcode/DerivedData/Runner-cphuoihdzwpgqgawumudiloeydqb/Build/Products/Debug-iphonesimulator/Mixpanel-swift/Mixpanel.framework/Modules/Mixpanel.swiftmodule

What do I need to update in order to get mixpanel to play nice?

This is from a flutter app using the mixpanel_flutter plugin version ^2.0.0.

**Comment by lirantzairi** [comment] 2023-03-31 01:27
Any update on this? I'm getting the same build error

**Comment by ashishkakkad8** [comment] 2023-05-04 07:12
In Xcode 14.3 if you are using Swift Package Manger then you will get following option "Build for Rosetta":

![Build for Rosetta](https://user-images.githubusercontent.com/6905345/236134833-4b8d6655-e7e0-43df-86ed-19596100e73d.png)

**Comment by jaredmixpanel** [comment] 2023-05-04 17:18
I'm not able to reproduce. All development of mixpanel-swift has taken place on Apple Silicon for some time now.

If I create a new project from Xcode 14.3 on my M1, add mixpanel-swift via SPM, import / initialize the library and track an event, it builds and works without issue. See below...

https://user-images.githubusercontent.com/10504508/236278890-6b2732d6-61c1-49e1-b37b-253098d5316f.mp4

**Comment by josejuanqm** [comment] 2023-05-10 16:34
I've found that if you're excluding arm64 as an architecture in your project you might come across this issue. try removing that setting from your build settings @JZ-at-TP

**Comment by jaredmixpanel** [comment] 2023-05-19 21:26
Closing this issue, unable to repro. If the issue persists, feel free to re-open with steps to reproduce.

**Closed by jaredmixpanel** 2023-05-19 21:26 UTC
