### ISSUE TITLE
AB Testing with Tweaks

### ISSUE THREAD

**Issue by FrancoisObob** [mixpanel/mixpanel-swift#81] opened 2017-04-25 16:12 UTC
Hi,
i actually want to use Mixpanel to do a simple AB Testing and a little tracking on my login form : 
 - 25% of users get the new login modal
 - 75% of users stay with the old one

To do so i just created a MixpanelTweak called showNewLogin of type Bool with a default value set to false.
Following the tutorial, i want to set up an experiment where 25% of users showNewLogin = true but can't figure it out how to do so in the Mixpanel A/B test designer. 

My experiment is not base on a visual element so why do i need to connect my device and display the UI to set an experiment ?
Where do i set the Tweak value associated to a % of users ?

Thanks a lot !

**Comment by didi4yeah** [comment] 2017-04-26 08:12
+1, was wondering same thing the other time

**Comment by cassiegamm** [comment] 2017-04-27 23:51
Hi @FrancoisObob,

The intention behind requiring the device to connect to the builder is to guard against typos (at least for tweak keys) and require developers to ensure that the tweak values are initialized correctly and modify the app as intended. 

To set the Tweak value associated to a % of users, connect the device, create two variants (one with the original value, the other with the experimental value) and click continue. This should cause a modal to pop up allowing you to customize the distribution like so:
<img width="539" alt="a_b_testing_-_mixpanel___mobile_analytics" src="https://cloud.githubusercontent.com/assets/8699478/25508141/fef4fa2a-2b64-11e7-9ac5-ac2f6be28c7c.png">

If you run into issues setting up or deploying your experiment, feel free to reach out to Support@mixpanel.com for some project specific help. 

If this device connection requirement prevents you from accomplishing your goals let us know - we always appreciate feedback that leads to a better product. Feel free to explain the issue in detail by sending me an email at (cassie@mixpanel.com).

**Comment by yarneo** [comment] 2017-05-16 22:57
Closing, thanks @cassiegamm !

**Closed by yarneo** 2017-05-16 22:57 UTC

**Comment by s3ton** [comment] 2019-02-12 14:46
I'm having the same issue as OP.
I can't seem to change the variable in the A/B test interface
Here is the part I can't seem to change:
https://i.ibb.co/6mdTdLD/Screenshot-2019-02-12-at-15-45-02.png
I want to set up the original with "1" and the variant with "2"
